### ISSUE TITLE
HUD Help tour dialogue is inconsistent on HUD and Center

### ISSUE THREAD

**Issue by mleeBoeing** [aml-development/ozp-hud#203]
- The HUD screen's help tour (HUD Section) should be consistent with the Center screens Help tour (HUD Section). 
- HUD Screen Help tour displays - "Opens HUD (heads up display) where your bookmarks are stored. Think of the HUD like the home screen on a smart phone." (INCORRECT)
- Center screen Help tour displays -  "Opens HUD (heads up display) where your bookmarked apps are stored, and can easily be organized and launched. Think of the HUD as your homepage for favorite apps" ( CORRECT) 
- HUD Screen Help Tour (Center Section)-Opens Center where you can search for listings to bookmark to your HUD or open in Webtop.(INCORRECT)
- Center Screen Help Tour (Center Section) - Opens the Center where you can search and discover app listings from across the IC. You can bookmark listings to your HUD and you can also launch apps into a seperate tab directly from the Center. ( CORRECT)
- HUD Screen Help Tour (Webtop Section) - Opens Webtop, your customizable workspace within the platform. (INCORRECT)
- Center Screen Hep Tour (Webtop Section) - Opens the Webtop, a virtual desktop environment. It allows you to run widgets in a single window, and save your custom workflows as dashboards.( CORRECT)

**Comment by flesher1** [comment]
Modifications made. No pull request made yet.

Evan

**Comment by flesher1** [comment]
Merged.
